language: go
go:
  - 1.9.2

services:
  - docker

sudo: required

before_install:
  - docker version

script:
  - sudo make -v
  - sudo make || exit 1
  - sudo make integration_tests || exit 1
  - sudo make acceptance_tests || exit 1

stages:
  - build
  - name: release
    if: branch = master

matrix:
  include:
    - stage: build
      env: CLIENT_VERSION=1
    - env: CLIENT_VERSION=2
    - env: CLIENT_VERSION=5
    - env: CLIENT_VERSION=6
    - stage: release
      script:
        - ./scripts/git-release.sh

after_install:
  - docker plugin ls