language: go
go:
  - 1.9.2

services:
  - docker

sudo: required

before_install:
  - docker version

script:
  - sudo make
  - sudo make integration_tests
  - sudo make acceptance_tests

matrix:
  include:
    - os: linux
      env: CLIENT_VERSION=2
    - os: linux
      env: CLIENT_VERSION=5

after_install:
  - docker plugin ls
  # TODO: add tag and publish docker plugin, if merged to master