language: go
go:
  - 1.9.2

services:
  - docker

sudo: required

before_install:
  - docker version

script:
  - sudo make -v
  - ./scripts/ci.sh

stages:
  - build
  - release

matrix:
  include:
    - stage: build
      env: CLIENT_VERSION=1
    - env: CLIENT_VERSION=2
    - env: CLIENT_VERSION=5
    - env: CLIENT_VERSION=6
    - stage: release
      branch:
        only:
          - master
      script:
        - ./scripts/git-release.sh

after_install:
  - docker plugin ls