---
version: '3'
services:
  elasticsearch:
    image: rchicoli/elasticsearch:5-tls
    volumes:
      - ../config/elasticsearch-v5.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - certs:/usr/share/elasticsearch/config/x-pack/certool:ro
    depends_on:
      - certool